<?php

namespace AppBundle\Domain\Repository;
use AppBundle\Domain\Entity\{
    Ticket
};

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
}
