<?php

namespace AppBundle\Domain\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTicketByDay($date)
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->where("t.entryAt LIKE :day")
            ->setParameter(':day', "$date%")
            ->getQuery()
            ->getSingleScalarResult();
    }
}
